package plg.generator.process;

public enum Metric {
    NUM_ACTIVITIES,
    NUM_GATEWAYS,
    NUM_AND_GATES,
    NUM_XOR_GATES,
    DIAMETER,
    COEFFICIENT_OF_NETWORK_CONNECTIVITY,
    SEQUENTIALITY,
    CONTROL_FLOW_COMPLEXITY,
    NUMBER_OF_CYCLES,
    TOKEN_SPLIT;

}
